### ISSUE TITLE
LIGHTHOUSE_CHROMIUM_PATH need to be set?

### ISSUE THREAD

**Issue by Raxxor** [gwuhaolin/koa-seo#1]
When I try to run demo, there is error: 
Error: The environment variable LIGHTHOUSE_CHROMIUM_PATH must be set to executable of a build of Chromium version 54.0 or later.

I suggest to deploy a docker file, so it is easy for other developers to use or contribute.

**Comment by gwuhaolin** [comment]
have you install chrome on you system?

this error is throw from lighthouse's [chrome-launcher](https://www.npmjs.com/package/chrome-launcher).

chrome-launcher will auto find a chrome in you system, if no chrome can be find, this error will be throw.

I will make a docker image later.

**Comment by Raxxor** [comment]
Thanks for your quick reply.
Problem sloved by install Chrome and set lighthouse_chromnium_path.

**Comment by gwuhaolin** [comment]
by the way, set env LIGHTHOUSE_CHROMIUM_PATH is not required, chrome-launcher will auto find a chrome in you system. if no chrome find, LIGHTHOUSE_CHROMIUM_PATH will be use.

**Comment by Raxxor** [comment]
:) I tried to set LIGHTHOUSE_CHROMIUM_PATH at first, and found it required chrome installed. I run headless chrome in docker before. So I install chrome-beta and it's OK.
