### ISSUE TITLE
Detecting browser window size

### ISSUE THREAD

**Issue by gajus** [gwuhaolin/koa-seo#3]
If you have a responsive application that will serve different content depending on the device resolution, then there is no reliable way to fetch a version specific to that device. Without this you will get DOM mismatch error when rendering the page on the client-side.

Opening an issue to start a conversation about possible solutions.

**Comment by gwuhaolin** [comment]
Your responsive application serve different content  depending on the User-Agent or browser window size? 
May we can add some options to [chrome-render](https://github.com/gwuhaolin/chrome-render):
- `User-Agent`: set http User-Agent header before request [doc](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setUserAgentOverride)
- `window-size`: set browser window size  [doc](https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setDeviceMetricsOverride)

dev can config it by themselves scenes.

**Comment by gwuhaolin** [comment]
support added in commit https://github.com/gwuhaolin/chrome-render/commit/32dc966ff3cf3ff59a2754b3f8f22f5fe97f110b in  chrome-render.
see https://github.com/gwuhaolin/chrome-render/issues/4
