### ISSUE TITLE
有考虑出个 express 版本的中间件吗

### ISSUE THREAD

**Issue by Binaryify** [gwuhaolin/koa-seo#5]

**Comment by gwuhaolin** [comment]
这个中间件的源码非常的少和简单，就这[一个文件](https://github.com/gwuhaolin/koa-seo/blob/master/index.js)谁都看的明白。
这个项目的主要逻辑都在
- [chrome-render](https://github.com/gwuhaolin/chrome-render)
- [chrome-pool](https://github.com/gwuhaolin/chrome-pool)
- [chrome-runner](https://github.com/gwuhaolin/chrome-runner)

我之所以把逻辑拆分在一个个独立的模块，就是为了这些模块可以用在其它项目上。
所以要做一个express中间件中间件非常简单，参考koa-seo调用chrome-render。如果你的产品用到express你可以封装一个贡献给大家，我先替大家感谢你。

**Comment by Binaryify** [comment]
已加入全家桶系列
https://github.com/Binaryify/express-middleware-seo

**Comment by gwuhaolin** [comment]
@Binaryify 很强很nice😘
