### ISSUE TITLE
将ua伪装成crawler怎么判断是否被爬

### ISSUE THREAD

**Issue by liSong5713** [gwuhaolin/koa-seo#7]
1.将ua伪装成crawler怎么判断是否被爬？
2.如果开启useReady，不设置window.isPageReady = 1,headless chrome会生成html吗？
多谢楼主帮助。

**Comment by gwuhaolin** [comment]
1. 这个问题很复杂，目前业界比较高级的方法运用到了机械学习；
2. 不会生成html，会timeout；
